### ISSUE TITLE
使用jdplay_open_sdk_android这个包出现闪退。

### ISSUE THREAD

**Issue by lb1207087645** [szjd/docs#2]
你好，我使用jdplay_open_sdk_android这个包时，运行Demo时，点击手机本地歌曲那一项时，出现闪退，调试代码发现查找本地音乐时返回空，但是我在背景音乐设备上已经在本地下了个mp3文件，没有检测到。

**Comment by luokj** [comment]
回到桌面，点击左侧切换到本地模式，点击刷新，将会扫描新加的歌曲
